version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server-dev.Dockerfile
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend-dev.Dockerfile
    command: yarn start
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
