[Settings]
  ID = "799c779d-861e-4009-95ba-86a56bdac424"

[Build]
  Publish = ""
  Functions = ""

[[redirects]]
  from = "search/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "product/*"
  to = "/index.html"
  status = 200
