version: 2

jobs:
  deploy_server:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy  server
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy_server:
          filters:
            branches:
              only: master
